### PR TITLE
Split fetch_asset

### PR DESCRIPTION
**Pull request by tgenin**
I try to simplify fetch_asset

I will add some tests for new split functions next week, but what to you think ?

### CODE REVIEW

**Comment by victorbenichoux** [comment]
There is likely some improvements to be had with this logic. Thanks for the submission

I will review next week!

**Comment by tgenin** [comment]
I add tests for created sub functions and remove the WIP flag. PTAL

**Comment by CyrilLeMat** [comment]
@antoinejeannot "we currently do not support windows-like filepaths" -> shouldn't we create an issue to reflect this ?

**Comment by victorbenichoux** [comment]
@antoinejeannot @CyrilLeMat 
We most certainly do support windows paths. The reason we sometimes split on unix separators is because *asset specifications* use `/` (as documented [here](https://cornerstone-ondemand.github.io/modelkit/assets/remote_assets/#asset-specification)), but they are correctly mapped to directories on windows. This is covered by tests.

This is exactly what the line that @antoinejeannot points to does:
```
os.path.exists(os.path.join(os.getcwd(), *asset_name.split("/")))
```
Split the asset specification `a/b/c` into a list, and join them with the OS specific separator with `os.path.join`.

This is the same paradigm as when referring to objects on object stores, which is where the assets specification convention comes from BTW 😄

**Comment by victorbenichoux** [comment]
Anyhow, LGTM, thanks @tgenin

**Review by victorbenichoux — APPROVED** [review]

**Comment by antoinejeannot** [comment]
@victorbenichoux never dig through it, nevermind :D (I also had a doubt, filepaths on windows always bugged me)
I am not sure the following's behaviour is intended though: `list(os.path.split(str(asset_dict["path"])))` before joining with "/"

**Comment by victorbenichoux** [comment]
@antoinejeannot where did you see that?

**Comment by antoinejeannot** [comment]
@victorbenichoux  https://github.com/Cornerstone-OnDemand/modelkit/pull/110#discussion_r745635004

**Pull request merged**
